version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce_aisyiya
      MYSQL_USER: kunam
      MYSQL_PASSWORD: manuk
    ports:
      - "3306:3306"

volumes:
  mysql-data: