version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb_db
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: ecommerce_aisyiya
      MARIADB_USER: kunam
      MARIADB_PASSWORD: manuk
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
